DROP TABLE IF EXISTS WHR_2015;
DROP TABLE IF EXISTS WHR_2016;
DROP TABLE IF EXISTS WHR_2017;
DROP TABLE IF EXISTS WHR_2018;
DROP TABLE IF EXISTS WHR_2019;
DROP TABLE IF EXISTS WHR_2020;
DROP TABLE IF EXISTS countries_regions;
DROP TABLE IF EXISTS whr;

-- Adding Tables

CREATE TABLE Countries_Regions
(
	Country VARCHAR(50) ,
	REGION VARCHAR(50)
);

copy Countries_Regions from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\CountryRegion.csv' with delimiter ',' csv header encoding 'windows-1251';

ALTER TABLE Countries_Regions
ADD COLUMN country_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;


CREATE TABLE WHR_2015 (
	Country VARCHAR(50),
	HappinessRank SMALLINT,
	HappinessScore DECIMAL(5,3),
	GDP DECIMAL(6,5),
	Family DECIMAL(6,5),
	LifeExpectancy DECIMAL(6,5),
	Freedom DECIMAL(6,5),
	Trust DECIMAL(6,5),
	Generosity DECIMAL(6,5)
	);
	
copy WHR_2015 from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\2015.csv' with delimiter ',' csv header encoding 'windows-1251'


	
CREATE TABLE WHR_2016 (
	Country VARCHAR(50),
	Region VARCHAR(50),
	HappinessRank SMALLINT,
	HappinessScore DECIMAL(5,3),
	GDP DECIMAL(6,5),
	Family DECIMAL(6,5),
	LifeExpectancy DECIMAL(6,5),
	Freedom DECIMAL(6,5),
	Trust DECIMAL(6,5),
	Generosity DECIMAL(6,5)
	);
	
copy whr_2016 from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\2016.csv' with delimiter ',' csv header encoding 'windows-1251';

	
CREATE TABLE WHR_2017 (
	Country VARCHAR(50),
	HappinessRank SMALLINT,
	HappinessScore DECIMAL(5,3),
	GDP DECIMAL(6,5),
	Family DECIMAL(6,5),
	LifeExpectancy DECIMAL(6,5),
	Freedom DECIMAL(6,5),
	Generosity DECIMAL(6,5),
	Trust DECIMAL(6,5)
	);
	
copy WHR_2017 from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\2017.csv' with delimiter ',' csv header encoding 'windows-1251';


CREATE TABLE WHR_2018 (
	Country VARCHAR(50),
	HappinessRank SMALLINT,
	HappinessScore DECIMAL(5,3),
	GDP DECIMAL(6,5),
	Family DECIMAL(6,5),
	LifeExpectancy DECIMAL(6,5),
	Freedom DECIMAL(6,5),
	Generosity DECIMAL(6,5),
	Trust DECIMAL(6,5)
	);
	
copy WHR_2018 from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\2018.csv' with delimiter ',' csv header encoding 'windows-1251';


CREATE TABLE WHR_2019 (
	Country VARCHAR(50),
	HappinessRank SMALLINT,
	HappinessScore DECIMAL(5,3),
	GDP DECIMAL(6,5),
	Family DECIMAL(6,5),
	LifeExpectancy DECIMAL(6,5),
	Freedom DECIMAL(6,5),
	Generosity DECIMAL(6,5),
	Trust DECIMAL(6,5)
	);

copy WHR_2019 from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\2019.csv' with delimiter ',' csv header encoding 'windows-1251';






CREATE TABLE WHR (
	country VARCHAR(50),
	Year CHAR(4),
	happinessrank smallint,
    happinessscore numeric(5,3),
    gdp numeric(6,5),
    family numeric(6,5),
    lifeexpectancy numeric(6,5),
    freedom numeric(6,5),
    trust numeric(6,5),
    generosity numeric(6,5)
	);
	

	
-- ADD A YEAR COLUMN TO THE TABLES 

ALTER TABLE whr_2015
ADD Year CHAR(4) NOT NULL
CONSTRAINT whr_2015_year DEFAULT 2015;

ALTER TABLE whr_2016
ADD Year CHAR(4) NOT NULL
CONSTRAINT whr_2016_year DEFAULT 2016;

ALTER TABLE whr_2017
ADD Year CHAR(4) NOT NULL
CONSTRAINT whr_2017_year DEFAULT 2017;

ALTER TABLE whr_2018
ADD Year CHAR(4) NOT NULL
CONSTRAINT whr_2018_year DEFAULT 2018;

ALTER TABLE whr_2019
ADD Year CHAR(4) NOT NULL
CONSTRAINT whr_2019_year DEFAULT 2019;





INSERT INTO whr(country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity)
SELECT country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity FROM whr_2015

SELECT * FROM whr_2015;
SELECT * FROM whr

INSERT INTO whr(country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity)
SELECT country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity FROM whr_2016;

INSERT INTO whr(country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity)
SELECT country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity FROM whr_2017;

INSERT INTO whr(country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity)
SELECT country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity FROM whr_2018;

INSERT INTO whr(country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity)
SELECT country,year,happinessrank,happinessscore,gdp,family,lifeexpectancy,freedom,trust,generosity FROM whr_2019;



--checking for null values

SELECT * FROM whr 
WHERE country IS null OR year IS null OR happinessrank IS null OR 
happinessscore IS null OR gdp IS null OR  family IS null OR 
lifeexpectancy IS null OR freedom IS null 
OR trust IS null OR generosity IS null

delete FROM whr
WHERE country = 'United Arab Emirates'


--Adding new metric

DROP TABLE IF EXISTS alcohol_cons;

CREATE TABLE Alcohol_Cons (
	country VARCHAR(100),
	year CHAR(4),
	liters NUMERIC(5,2)
);

SELECT * FROM Alcohol_Cons

copy Alcohol_Cons from 'C:\Users\saleh\Desktop\UCB Bootcamp\Final Project\Data\data_alcohol_clean.csv' with delimiter ',' csv header encoding 'windows-1251';

DELETE FROM Alcohol_Cons
WHERE country = 'United Arab Emirates'

-- Checking for null values
SELECT COUNT(AC.country) FROM Alcohol_cons AS AC
FULL OUTER JOIN whr ON AC.country = whr.country
WHERE AC.country is null OR whr.country is null 

-- Deleting 2020 data 
DELETE FROM whr
WHERE year = '2020'


SELECT DISTINCT country FROM whr

EXCEPT

SELECT DISTINCT Country FROM alcohol_cons 


-- 33 Countries do not math the WHR table

SELECT AC.country , whr.country FROM Alcohol_cons AS AC
FULL OUTER JOIN whr ON AC.country = whr.country
WHERE AC.country is null OR whr.country is null 
